server:
  port: 6666
  servlet:
    context-path: /xcx
  connection-timeout: 10000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xcx?characterEncoding=UTF-8
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    hikari:
      idleTimeout: 60000
      connectionTimeout: 60001
      validationTimeout: 3000
      loginTimeout: 5
      maxLifetime: 60000
      readOnly: false
      maximumPoolSize: 60
      minimumIdle: 10
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
    host: 127.0.0.1
    port: 6379
    password: sessiontech
    # 连接超时时间（毫秒）
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
    timeout:  3000

file:
  physicalPath: C:/web/xcx/test/file
  networkPath: http://127.0.0.1:6666/xcx
  staticAccessPath: /xcxsk/**
  absolutePath: file:C:/web/xcx/test/file/xcxsk/

##微信配置
wechat:
  appID: ***
  appsecret: ***
pj:
  wechatMpAuthorize: http://xbcai.natapp1.cc

##小程序配置
xcx:
  appid: ***
  secret: ***
  grantType: authorization_code

log:
  path: E:/log/xcx/test
  level: DEBUG